### ISSUE TITLE
TypeError: utils.forOwn is not a function

### ISSUE THREAD

**Issue by TheGP** [dougwithseismic/npm-definitely-not-a-robot#1]
After building the package from git repo (`npm run build:js && npm run build:types` or `npm run build`)

I get this error while trying to use it
```
node app.js
/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:80852
        utils.forOwn(obj, function(obj2, key) {
              ^

TypeError: utils.forOwn is not a function
    at cloneObjectDeep (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:80852:15)
    at cloneDeep (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:80842:18)
    at mergeDeep (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:80998:20)
    at new PuppeteerExtraPlugin (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:81052:22)
    at new StealthPlugin2 (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:81515:9)
    at defaultExport (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:81598:35)
    at Object.<anonymous> (/home/eugenebos/Websites/reviews/automation/definitely-not-a-robot/npm-definitely-not-a-robot/dist/index.js:81856:86)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)

Node.js v20.10.0
```

**Comment by eng3** [comment]
I run into the same issue after building and trying to use it.  I would like to use it with a node project

**Comment by dougwithseismic** [comment]
Hey all, this was small project I put together for fun and forgot about
completely. I'll be able to look at this (and other issues) next week if
it's of interest!

**Comment by eng3** [comment]
That would be great!  It sounds very promising to tackle anti-bot behavior.  Ofcourse I won't know if it is useful for me until I can actually try it.  If you an also provide more detailed instructions building and getting it to work with node, that would be great too


btw, this may be useful https://github.com/oven-sh/bun/issues/3823

**Comment by TheGP** [comment]
@eng3 you can check out this: https://github.com/TheGP/Imposter (but the documentation is outdated already, use ChatGPT to generate). I learned that cursor movements in this repo are bizarre, so I ditched it for ghost-cursor (and added hesitation to it as this project has it)

**Comment by eng3** [comment]
@TheGP Thanks, I'll take a look.  Does it import straight into node.js code?  Have you actually found the mouse movements have made a difference.  (have found found anti-bot detection that looks for this?)

**Comment by TheGP** [comment]
@TheGP its nodejs too, nope, ghost cursor is not that great as well.
